### ISSUE TITLE
First "NewRun" command implicit 

### ISSUE THREAD

**Issue by k2d222** [Aerll/rpp#32]
In ddnet, the first `NewRun` instruction is implicit: after the config name, a run is started. On the contrary in rules++, the first `NewRun();` is mandatory. (which is fine, although I'd prefer implicit runs as well) but the code generated contains a `NewRun`, which is actually a 2nd run (the first, implicit run does nothing).

TLDR It would be better to remove the first `NewRun` in generated `.rules` files, or to make the first `NewRun();` instruction implicit. 

Example:

```
#include "base.r"
#tileset "generic_unhookable"

AutoMapper("Sweeper");
NewRun();

Insert(0);
```
generates

```
[Sweeper]

NewRun

Index 0 
```
but should have generated 
```
[Sweeper]

Index 0
```

**Comment by Aerll** [comment]
I reverted this change. There's really no reason to have it and only bloats the generating code with formatting.
